seed: 42
run_name: debug_2k
device: cuda

data:
  train_csv: data/processed/debug_2k.csv
  val_csv: data/processed/debug_2k.csv
  test_csv: data/processed/debug_2k.csv
  image_size: 224
  batch_size: 16
  num_workers: 0
  balanced_sampler: true

model:
  name: baseline_mbv3
  pretrained: false
  dropout: 0.2

loss:
  lambda_spoof: 0.0
  lambda_illum: 0.0
  lambda_env: 0.0
  gamma_proto: 0.0

train:
  epochs: 2
  lr: 0.0003
  weight_decay: 0.0001
  amp: true
  early_stop_patience: 2
  metric_to_select: val_acer

output:
  run_dir: outputs/runs/debug_2k